version: '3'
services:
  ingress:
    image: davidschneiderinfo/nginx
    build:
      context: ./docker/nginx
      dockerfile: Dockerfile
    ports:
      - '${NGINX_PORT:-80}:80'
    volumes:
      - ./config/ingress/default.conf:/etc/nginx/conf.d/default.conf
      - ./logs/ingress:/var/log/nginx
    networks:
      - service-network
  blog-nginx:
    image: davidschneiderinfo/blog-nginx
    build:
      context: ./docker/nginx
      dockerfile: Dockerfile
    volumes:
      - ./apps/blog:/var/www
      - ./logs/blog-nginx:/var/log/nginx
    networks:
      - service-network
    depends_on:
      - blog-php
    links:
      - "blog-php:php"
  blog-php:
    image: davidschneiderinfo/blog-php
    build:
      context: ./docker/php
      dockerfile: Dockerfile
    environment:
      - DB_DATABASE=blog
      - DB_USERNAME=root
      - 'DB_PASSWORD=${DB_PASSWORD:-secret}'
    volumes:
      - ./apps/blog:/var/www
      - ./logs/blog-php:/var/www/storage/logs
    networks:
      - service-network
  prototype-nginx:
    image: davidschneiderinfo/prototype-nginx
    build:
      context: ./apps/nginx
      dockerfile: ./apps/prototype/docker/nginx/Dockerfile
    volumes:
      - ./apps/prototype:/var/www
      - ./logs/prototype-nginx:/var/log/nginx
    networks:
      - service-network
    depends_on:
      - prototype-php
    links:
      - "prototype-php:php"
  prototype-php:
    image: davidschneiderinfo/prototype-php
    build:
      context: ./apps/prototype
      dockerfile: ./apps/prototype/docker/php/Dockerfile
    environment:
      - DB_DATABASE=prototype
      - DB_USERNAME=root
      - 'DB_PASSWORD=${DB_PASSWORD:-secret}'
    volumes:
      - ./apps/prototype:/var/www
      - ./logs/prototype-php:/var/www/storage/logs
    networks:
      - service-network
  mysql:
    image: 'mysql/mysql-server:8.0'
    ports:
      - '${FORWARD_DB_PORT:-3306}:3306'
    environment:
      MYSQL_ROOT_PASSWORD: '${DB_PASSWORD:-secret}'
      MYSQL_ROOT_HOST: "%"
      MYSQL_USER: '${DB_USER:-operator}'
      MYSQL_PASSWORD: '${DB_PASSWORD:-secret}'
      MYSQL_ALLOW_EMPTY_PASSWORD: 1
    volumes:
      - 'service-mysql:/var/lib/mysql'
      - ./config/mysql/initdb.d:/docker-entrypoint-initdb.d
    networks:
      - service-network
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-p${DB_PASSWORD:-secret}"]
      retries: 3
      timeout: 5s
  redis:
    image: 'redis:alpine'
    ports:
      - '${FORWARD_REDIS_PORT:-6379}:6379'
    volumes:
      - 'service-redis:/data'
    networks:
      - service-network
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      retries: 3
      timeout: 5s
  mailhog:
    image: 'mailhog/mailhog:latest'
    ports:
      - '${FORWARD_MAILHOG_PORT:-1025}:1025'
      - '${FORWARD_MAILHOG_DASHBOARD_PORT:-8025}:8025'
    networks:
      - service-network
  jenkins:
    image: jenkins/jenkins:lts
    privileged: true
    user: root
    container_name: jenkins
    ports:
      - '8080:8080'
      - '50000:50000'
    volumes:
      - ./.jenkins:/var/jenkins_home
      - /var/run/docker.sock:/var/run/docker.sock
      - /usr/bin/docker:/usr/local/bin/docker
    networks:
      - service-network
  agent:
    build:
      context: ./docker/builder
      dockerfile: Dockerfile
    image: davidschneiderinfo/jenkins-builder
    privileged: true
    user: root
    container_name: agent
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - /usr/bin/docker:/usr/local/bin/docker
    expose:
      - 22
    environment:
      - "JENKINS_AGENT_SSH_PUBKEY=${JENKINS_AGENT_SSH_PUBKEY}"
    networks:
      - service-network
    depends_on:
      - jenkins
networks:
  service-network:
    driver: bridge
volumes:
  service-mysql:
    driver: local
  service-redis:
    driver: local