version: '3'
services:
  ingress:
    image: davidschneiderinfo/nginx
    build:
      context: ./docker/nginx
      dockerfile: Dockerfile
    ports:
      - '${NGINX_PORT:-80}:80'
    volumes:
      - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
      - ./logs/ingress:/var/log/nginx
    networks:
      - service-network
    hostname: "${DOMAIN_NAME}"
    links:
      - "blog-nginx:blog"
  blog-nginx:
    image: davidschneiderinfo/blog-nginx
    build:
      context: ./apps/blog/docker/nginx
      dockerfile: Dockerfile
    volumes:
      - ./apps/blog:/var/www
      - ./logs/blog-nginx:/var/log/nginx
    networks:
      - service-network
    hostname: "blog.${DOMAIN_NAME}"
    depends_on:
      - blog-php
    links:
      - "blog-php:php"
  blog-php:
    environment:
      - "DOMAIN_NAME=${DOMAIN_NAME}"
    image: davidschneiderinfo/blog-php
    build:
      context: ./apps/blog/docker/php
      dockerfile: Dockerfile
    volumes:
      - ./apps/blog:/var/www
      - ./logs/blog-php:/var/www/storage/logs
    networks:
      - service-network
  mysql:
    image: 'mysql/mysql-server:8.0'
    ports:
      - '${FORWARD_DB_PORT:-3306}:3306'
    environment:
      MYSQL_ROOT_PASSWORD: '${DB_PASSWORD}'
      MYSQL_ROOT_HOST: "%"
      MYSQL_DATABASE: '${DB_DATABASE}'
      MYSQL_USER: '${DB_USERNAME}'
      MYSQL_PASSWORD: '${DB_PASSWORD}'
      MYSQL_ALLOW_EMPTY_PASSWORD: 1
    volumes:
      - 'service-mysql:/var/lib/mysql'
    networks:
      - service-network
    hostname: "mysql.${DOMAIN_NAME}"
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-p${DB_PASSWORD}"]
      retries: 3
      timeout: 5s
  redis:
    image: 'redis:alpine'
    ports:
      - '${FORWARD_REDIS_PORT:-6379}:6379'
    volumes:
      - 'service-redis:/data'
    networks:
      - service-network
    hostname: "redis.${DOMAIN_NAME}"
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      retries: 3
      timeout: 5s
  mailhog:
    image: 'mailhog/mailhog:latest'
    ports:
      - '${FORWARD_MAILHOG_PORT:-1025}:1025'
      - '${FORWARD_MAILHOG_DASHBOARD_PORT:-8025}:8025'
    networks:
      - service-network
    hostname: "mailhog.${DOMAIN_NAME}"
  npm:
    image: davidschneiderinfo/node
    volumes:
      - ./apps/blog:/var/www
  composer:
    image: davidschneiderinfo/composer
    volumes:
      - ./apps/blog:/var/www

networks:
  service-network:
    driver: bridge
volumes:
  service-mysql:
    driver: local
  service-redis:
    driver: local
